[browser]
gatherUsageStats = false

[client]
showErrorDetails = "full"

[theme]
primaryColor = "#ff6926"
backgroundColor = "#f7f9ff"
secondaryBackgroundColor = "#e3efff"
textColor = "#001d33"

[server]
fileWatcherType = "auto"
headless = true
